#!/bin/bash

PS3='Choose choice ?: '
options=("kill-80" "npm add watcher limit" "Who am i ?" "Seeme Start" "Exit")
select opt in "${options[@]}"
do
    case $opt in
        "kill-80")
            sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill
            echo "Success killed";
            ;;
        "npm add watcher limit")
            echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
            ;;
        "Who am i ?")
            echo $USER
            ;;
        "Seeme Start")
            gnome-terminal --tab --title="docker-compose up" -- bash -c 'cd ~/Documents/SeemeTask/hd-compose && docker-compose up'
            gnome-terminal --tab --title="npm run watch" -- bash -c 'cd ~/Documents/SeemeTask/seeme-web && npm run watch'
            ;;
        "Exit")
            break
            ;;
        *)     printf '\n'

    echo "Nani !!!!!!!"

    printf '\n'

    echo "       ▒▒▒▒▒▒▒█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
       ▒▒▒▒▒▒▒█░▒▒▒▒▒▒▒▓▒▒▓▒▒▒▒▒▒▒░█
       ▒▒▒▒▒▒▒█░▒▒▓▒▒▒▒▒▒▒▒▒▄▄▒▓▒▒░█░▄▄
       ▒▒▄▀▀▄▄█░▒▒▒▒▒▒▓▒▒▒▒█░░▀▄▄▄▄▄▀░░█
       ▒▒█░░░░█░▒▒▒▒▒▒▒▒▒▒▒█░░░░░░░░░░░█
       ▒▒▒▀▀▄▄█░▒▒▒▒▓▒▒▒▓▒█░░░█▒░░░░█▒░░█
       ▒▒▒▒▒▒▒█░▒▓▒▒▒▒▓▒▒▒█░░░░░░░▀░░░░░█
       ▒▒▒▒▒▄▄█░▒▒▒▓▒▒▒▒▒▒▒█░░█▄▄█▄▄█░░█
       ▒▒▒▒█░░░█▄▄▄▄▄▄▄▄▄▄█░█▄▄▄▄▄▄▄▄▄█
       ▒▒▒▒█▄▄█░░█▄▄█░░░░░░█▄▄█░░█▄▄█"

    printf '\n';;
    esac
done
